Poisson likelihood
JaxGaussianProcesses/GPJax pull request #231
Opened 2023-04-13 15:29 UTC by frazane

Adds the Poisson likelihood. I'm not 100% sure the link function is correct, if someone could double check it would be great. 

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2023-04-13 18:47 UTC, Daniel-Dodd commented on gpjax/likelihoods.py
> +
Looks good, but just a thought - is the `log_rate` argument more stable?

2023-04-13 19:11 UTC, Daniel-Dodd commented on gpjax/likelihoods.py
> +
After a brief look at the source code, the answer seems to be no.

2023-04-17 15:29 UTC, thomaspinder requested changes
Nice work! Two things that would be nice:
1) A test to check that a non-conjugate GP is returned from taking the product of the prior and Poisson likelihood.
2) A notebook demonstrating this. Simulated data would be fine and it could heavily draw on the MCMC routine used in the classification notebook.

2023-04-28 19:37 UTC, thomaspinder requested changes

2023-04-28 19:37 UTC, thomaspinder commented on examples/poisson.pct.py
> +# # Count data regression with the Poisson likelihood
Could we name this something short like "Count data regression"? It renders nicer in the docs' table of contents this way.

2023-04-28 19:37 UTC, thomaspinder commented on examples/poisson.pct.py
> +key = jr.PRNGKey(123)
Could you please add the following to hook into Beartype?
```
with install_import_hook("gpjax", "beartype.beartype"):
    import gpjax as gpx
```

2023-04-28 19:37 UTC, thomaspinder commented on examples/poisson.pct.py
> +I = jnp.eye
let's name this `identity_matrix` or simply use `jnp.eye`. Single letter variables are discouraged in PEP rules.

2023-04-28 19:37 UTC, thomaspinder commented on examples/poisson.pct.py
> +# For count data regression, the Poisson distribution is a natural choice. The probability mass function of the Poisson distribution is given by
nit: _"is a natural choice for the likelihood function."_.

2023-04-28 19:37 UTC, thomaspinder commented on examples/poisson.pct.py
> +# where $y$ is the count and the parameter $\lambda$ is the rate of the Poisson distribution.
nit: `\lambda \in \mathbb{R}_{>0}`

2023-04-28 19:37 UTC, thomaspinder commented on examples/poisson.pct.py
> +# We than set $\lambda = \exp(f)$ where $f$ is the latent Gaussian process. The exponential function is the _link function_ for the Poisson distribution: it maps the output of a GP to the positive re
Nice.

2023-04-28 19:37 UTC, thomaspinder commented on examples/poisson.pct.py
> +# %watermark -n -u -v -iv -w -a "Thomas Pinder & Daniel Dodd (edited by Francesco Zanetta)"
You probably want to change - you wrote this notebook :)

2023-04-29 09:19 UTC, thomaspinder approved these changes

2023-04-29 09:20 UTC, merged