Update contribution documentation
JaxGaussianProcesses/GPJax pull request #329
Opened 2023-07-03 21:21 UTC by Thomas-Christie

Updated documentation for contributing to reflect the change to using Poetry for dependency management. Also added the command for manually running the pre-commit hook to the documentation.

Also fixed a few broken links and typos I had encountered.

## Type of changes

- [ ] Bug fix
- [ ] New feature
- [X] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [X] I've formatted the new code by running `poetry run pre-commit run --all-files --show-diff-on-failure` before committing.
- [X] I've added tests for new code.
- [X] I've added docstrings for the new code.

## Description

Poetry is now used for dependency management, but the documentation for contributing hadn't been updated to reflect this. Therefore, the documentation for contributing has been updated to reflect this change. A few broken links and typos have also been fixed.

Issue Number: N/A

2023-07-04 09:25 UTC, Thomas-Christie commented
@thomaspinder tagging for review as I'm unable to add you as a reviewer.

2023-07-04 15:16 UTC, thomaspinder commented on docs/contributing.md
> +development. Once the virtual environment is activated, run:
```suggestion
development. For those using Apple Silicon chips, we advise using [Conda miniforge](https://github.com/conda-forge/miniforge). Once the virtual environment is activated, run:
```

2023-07-04 15:17 UTC, thomaspinder requested changes
Looks great @Thomas-Christie. Just a small comment from me re. users with M1 chips; a topic we've received several questions about.

2023-07-04 16:30 UTC, Thomas-Christie commented
Thanks for the review @thomaspinder, I have added the change you suggested.

2023-07-05 08:00 UTC, thomaspinder approved these changes

2023-07-05 08:01 UTC, thomaspinder commented
Great work @Thomas-Christie. You can merge this now.

2023-07-05 08:39 UTC, merged